name: konduit
version: "0.2.1"
description: "Helm meets Kustomize, but without the YAML."
platformCommand:
  - os: windows
    command: $HELM_PLUGIN_DIR/bin/konduit.exe
  - command: $HELM_PLUGIN_DIR/bin/konduit
platformHooks:
  install:
    - command: $HELM_PLUGIN_DIR/scripts/install-helm-plugin.sh
  update:
    - command: $HELM_PLUGIN_DIR/scripts/install-helm-plugin.sh
