// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockEvaluator creates a new instance of MockEvaluator. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockEvaluator(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockEvaluator {
	mock := &MockEvaluator{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockEvaluator is an autogenerated mock type for the Evaluator type
type MockEvaluator struct {
	mock.Mock
}

type MockEvaluator_Expecter struct {
	mock *mock.Mock
}

func (_m *MockEvaluator) EXPECT() *MockEvaluator_Expecter {
	return &MockEvaluator_Expecter{mock: &_m.Mock}
}

// Evaluate provides a mock function for the type MockEvaluator
func (_mock *MockEvaluator) Evaluate(files []string) ([]byte, error) {
	ret := _mock.Called(files)

	if len(ret) == 0 {
		panic("no return value specified for Evaluate")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]string) ([]byte, error)); ok {
		return returnFunc(files)
	}
	if returnFunc, ok := ret.Get(0).(func([]string) []byte); ok {
		r0 = returnFunc(files)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func([]string) error); ok {
		r1 = returnFunc(files)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockEvaluator_Evaluate_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Evaluate'
type MockEvaluator_Evaluate_Call struct {
	*mock.Call
}

// Evaluate is a helper method to define mock.On call
//   - files []string
func (_e *MockEvaluator_Expecter) Evaluate(files interface{}) *MockEvaluator_Evaluate_Call {
	return &MockEvaluator_Evaluate_Call{Call: _e.mock.On("Evaluate", files)}
}

func (_c *MockEvaluator_Evaluate_Call) Run(run func(files []string)) *MockEvaluator_Evaluate_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 []string
		if args[0] != nil {
			arg0 = args[0].([]string)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockEvaluator_Evaluate_Call) Return(result []byte, err error) *MockEvaluator_Evaluate_Call {
	_c.Call.Return(result, err)
	return _c
}

func (_c *MockEvaluator_Evaluate_Call) RunAndReturn(run func(files []string) ([]byte, error)) *MockEvaluator_Evaluate_Call {
	_c.Call.Return(run)
	return _c
}

// SupportedFileExt provides a mock function for the type MockEvaluator
func (_mock *MockEvaluator) SupportedFileExt() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for SupportedFileExt")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockEvaluator_SupportedFileExt_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SupportedFileExt'
type MockEvaluator_SupportedFileExt_Call struct {
	*mock.Call
}

// SupportedFileExt is a helper method to define mock.On call
func (_e *MockEvaluator_Expecter) SupportedFileExt() *MockEvaluator_SupportedFileExt_Call {
	return &MockEvaluator_SupportedFileExt_Call{Call: _e.mock.On("SupportedFileExt")}
}

func (_c *MockEvaluator_SupportedFileExt_Call) Run(run func()) *MockEvaluator_SupportedFileExt_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockEvaluator_SupportedFileExt_Call) Return(s string) *MockEvaluator_SupportedFileExt_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockEvaluator_SupportedFileExt_Call) RunAndReturn(run func() string) *MockEvaluator_SupportedFileExt_Call {
	_c.Call.Return(run)
	return _c
}
