// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	"github.com/jace-ys/konduit/internal/exec"
	mock "github.com/stretchr/testify/mock"
)

// NewMockRunner creates a new instance of MockRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRunner {
	mock := &MockRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRunner is an autogenerated mock type for the Runner type
type MockRunner struct {
	mock.Mock
}

type MockRunner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRunner) EXPECT() *MockRunner_Expecter {
	return &MockRunner_Expecter{mock: &_m.Mock}
}

// Run provides a mock function for the type MockRunner
func (_mock *MockRunner) Run(ctx context.Context, command string, args []string, opts ...exec.RunOption) error {
	var tmpRet mock.Arguments
	if len(opts) > 0 {
		tmpRet = _mock.Called(ctx, command, args, opts)
	} else {
		tmpRet = _mock.Called(ctx, command, args)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, []string, ...exec.RunOption) error); ok {
		r0 = returnFunc(ctx, command, args, opts...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRunner_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockRunner_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - ctx context.Context
//   - command string
//   - args []string
//   - opts ...exec.RunOption
func (_e *MockRunner_Expecter) Run(ctx interface{}, command interface{}, args interface{}, opts ...interface{}) *MockRunner_Run_Call {
	return &MockRunner_Run_Call{Call: _e.mock.On("Run",
		append([]interface{}{ctx, command, args}, opts...)...)}
}

func (_c *MockRunner_Run_Call) Run(run func(ctx context.Context, command string, args []string, opts ...exec.RunOption)) *MockRunner_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		var arg1 string
		if args[1] != nil {
			arg1 = args[1].(string)
		}
		var arg2 []string
		if args[2] != nil {
			arg2 = args[2].([]string)
		}
		var arg3 []exec.RunOption
		var variadicArgs []exec.RunOption
		if len(args) > 3 {
			variadicArgs = args[3].([]exec.RunOption)
		}
		arg3 = variadicArgs
		run(
			arg0,
			arg1,
			arg2,
			arg3...,
		)
	})
	return _c
}

func (_c *MockRunner_Run_Call) Return(err error) *MockRunner_Run_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRunner_Run_Call) RunAndReturn(run func(ctx context.Context, command string, args []string, opts ...exec.RunOption) error) *MockRunner_Run_Call {
	_c.Call.Return(run)
	return _c
}
